version: "3.5"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./project:/home/node/app
    ports:
      - "4444:3000"
    command: "npm run start:dev"
    networks:
      - frontend
      - backend
  mongo:
    image: "mongo:4.0.4"
    restart: always
    volumes:
      - ./db/mongo/data/db:/data/db
    ports:
      - "4445:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend
  redis:
    image: "redis:5"
    restart: always
    volumes:
      - ./db/redis:/data
    networks:
      - backend
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    volumes:
      - ./db/minio:/data
    environment:
      MINIO_ACCESS_KEY: caseywang
      MINIO_SECRET_KEY: wangyang_1991
    command: "server /data"
    networks:
      - frontend
      - backend
networks:
  frontend:
    name: blog_frontend
    driver: bridge
  backend:
    name: blog_backend
    driver: bridge
